/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/lib/shadcn/ui/badge/Badge.vue')['default']
    BarChart: typeof import('./src/lib/shadcn/ui/chart-bar/BarChart.vue')['default']
    Button: typeof import('./src/lib/shadcn/ui/button/Button.vue')['default']
    Card: typeof import('./src/lib/shadcn/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/lib/shadcn/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/lib/shadcn/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/lib/shadcn/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/lib/shadcn/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/lib/shadcn/ui/card/CardTitle.vue')['default']
    ChartCrosshair: typeof import('./src/lib/shadcn/ui/chart/ChartCrosshair.vue')['default']
    ChartLegend: typeof import('./src/lib/shadcn/ui/chart/ChartLegend.vue')['default']
    ChartSingleTooltip: typeof import('./src/lib/shadcn/ui/chart/ChartSingleTooltip.vue')['default']
    ChartTooltip: typeof import('./src/lib/shadcn/ui/chart/ChartTooltip.vue')['default']
    Dashboard: typeof import('./src/domains/dashboard/pages/Dashboard/Dashboard.vue')['default']
    DashboardAnalytics: typeof import('./src/domains/dashboard/pages/DashboardAnalytics/DashboardAnalytics.vue')['default']
    DashboardCard: typeof import('./src/domains/dashboard/components/DashboardCard/DashboardCard.vue')['default']
    DashboardChartBar: typeof import('./src/domains/dashboard/components/DashboardChartBar/DashboardChartBar.vue')['default']
    DashboardHeader: typeof import('./src/domains/dashboard/components/DashboardHeader/DashboardHeader.vue')['default']
    DashboardHours: typeof import('./src/domains/dashboard/pages/DashboardHours/DashboardHours.vue')['default']
    DashboardHoursData: typeof import('./src/domains/dashboard/pages/DashboardHours/DashboardHoursData/DashboardHoursData.vue')['default']
    DashboardLayout: typeof import('./src/domains/dashboard/components/DashboardLayout/DashboardLayout.vue')['default']
    DataProvider: typeof import('./src/domains/functional/components/DataProvider/DataProvider.vue')['default']
    DataProviderError: typeof import('./src/domains/functional/components/DataProvider/DataProviderError.vue')['default']
    DataProviderLoading: typeof import('./src/domains/functional/components/DataProvider/DataProviderLoading.vue')['default']
    Error: typeof import('./src/domains/functional/components/DataProvider/Error.vue')['default']
    Heading: typeof import('./src/domains/functional/components/Heading/Heading.vue')['default']
    Icon: typeof import('./src/domains/functional/components/Icon/Icon.vue')['default']
    Label: typeof import('./src/lib/shadcn/ui/label/Label.vue')['default']
    LineChart: typeof import('./src/lib/shadcn/ui/chart-line/LineChart.vue')['default']
    Loading: typeof import('./src/domains/functional/components/DataProvider/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/lib/shadcn/ui/switch/Switch.vue')['default']
    User: typeof import('./src/domains/user/pages/User/User.vue')['default']
  }
}
